#!/usr/bin/python

import	os
import	sys

class	SysSys( object ):

	def	__init__( self, prefix = '/etc' ):
		self.prefix = prefix

	def	doit( self, fn = 'syssys.conf' ):
		file = os.path.join( self.prefix, fn )
		try:
			f = open( file, 'rt' )
		except Exception, e:
			print >>sys.stderr, 'Cannot open file "%s".' % file
			return False
		retval = True
		for line in f:
			tokens = line.strip().split('#',1)[0].split('=',1)
			if len(tokens) == 2:
				name    = tokens[0].strip()
				value   = tokens[1].strip()
				setting = os.path.join( '/sys', name.replace( '.', os.sep ) )
				try:
					param = open( setting, 'wt' )
				except Exception, e:
					print >>sys.stderr, 'No such setting "%s".' % name
					retval = False
					continue
				try:
					print >>param, value
				except Exception, e:
					print >>sys.stderr, 'Cannot set "%s" to "%s".' % (
						name,
						value
					)
					param.close()
					retval = False
					continue
				param.close()
		f.close()
		return retval

if __name__ == '__main__':
	ss = SysSys()
	if not ss.doit():
		exit(1)
	exit(0)
